MINOR: Correct usage of ConfigException in file and directory config providers
The two-arg variant is intended to take a property name and value, not an exception message and a cause.

As-is, this leads to confusing log messages like:

```
org.apache.kafka.common.config.ConfigException: Invalid value java.nio.file.NoSuchFileException: /my/missing/secrets.properties for configuration Could not read properties from file /my/missing/secrets.properties
```

Author: Chris Egerton <chrise@confluent.io>

Reviewers: Gwen Shapira

Closes #11555 from C0urante/patch-1