HOTFIX: Fix compile error in TopicAdminTest (#8866)
Commit c0d5968ccd8a902532d9270366ff95ebe51969a0 changed the constructor of DescribeConfigsResponse.

The build failed with the following error: 
```
/home/chia7712/kafka/connect/runtime/src/test/java/org/apache/kafka/connect/util/TopicAdminTest.java:582: error: incompatible types: int cannot be converted to Struct
        return new DescribeConfigsResponse(1000, configs);
                                           ^
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
1 error
```

Reviewers: Boyang Chan <boyang@confluent.io>, Tom Bentley <tbentley@redhat.com>, Konstantine Karantasis <konstantine@confluent.io>